Resolve merge conflict in scraper
i did this after getting message: "Run python scraper.py
  File "/home/runner/work/job-scraper/job-scraper/scraper.py", line 27
    >>>>>>> 2c42fdb62eebdebd2ab0db5389e75532f4669810
            ^
SyntaxError: invalid decimal literal
Error: Process completed with exit code 1."